version: "3.8"

services:
  yapad-discord-bot:
    build: .
    container_name: yapad-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - yapad-data:/app/data
    networks:
      - yapad-net

volumes:
  yapad-data:

networks:
  yapad-net:
    driver: bridge
